[ww]
user = ww-data
group = ww-data
listen = 0.0.0.0:9000
listen.owner = ww-data
listen.group = ww-data
pm = dynamic
pm.max_children = 25
pm.start_servers = 5
pm.min_spare_servers = 1
pm.max_spare_servers = 10